services:
  bot:
    container_name: tarolog_bot
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./tarolog:/tarolog
      - ./metrics:/metrics
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 128M
